billing/urls.py
#This is blocbox/billing/urls.py
from django.conf.urls import patterns, include, url
from core import views #it imports views from blocbox modeule so knows where to look for index files
#from django.conf.urls.defaults import * #that was in the paypal ipn
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from billing import views 
from paypal.standard.ipn import views
admin.autodiscover()


#url patterns preceded by blocbox.co/payment - the namespace is payment, so need to reverse call with, eg payment:paypal_ipn
urlpatterns = patterns('',
		#Base views - defined in billing/views.py
		url(r'^$', 'paypal.standard.ipn.views.ask_for_money', name='payment_default'), #blocbox.co/payment, defaults o host_id=2 which is John
		url(r'^host(?P<host_id>\d+)/$', 'billing.views.base', name='billingbase'), #blocbox.co/payment/host2
		url(r'^host(?P<host_id>\d+)/days(?P<dayrangestart>\d+)to(?P<dayrangeend>\d+)/$', 'billing.views.base', name='billingbase'), 
		#STANDARD-IPN URLs - view in paypal/standard/ipn/views.py		
		url(r'^host(?P<host_id>\d+)/ipn/(?P<favortype>\w+)/(?P<paymentoption>\w+)/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask'), #blocbox.co/payment/host2/<TYPE?
		url(r'^host(?P<host_id>\d+)/days(?P<dayrangestart>\d+)to(?P<dayrangeend>\d+)/ipn/(?P<favortype>\w+)/(?P<paymentoption>\w+)/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask'),
		url(r'^ipn/host(?P<host_id>\d+)/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask_noamount'), #blocbox.co/payment/host2 - not really relevant - Default - Package Amount
		url(r'^ipn/notify(?P<host_id>\d+)/$', 'paypal.standard.ipn.views.ipn', name='paypal_ipn_notify'), #this is the notify_url	
		url(r'^ipn/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask_nohost'), #blocbox.co/payment/ipn - NOT FUNCTION B/C DOESN'T LINK TO HOST
    url(r'^ipn/return/$', 'paypal.standard.ipn.views.ipn_return_successful', name='ipn_return_successful'), #Eventually may need a return URL
    #STANDARD-PDT URLS
    #PRO URLS
    #url(r'^pro$', 'billing.views.paypal_pro', name='billingpro'), #no real purpose to this bc not linked to a host
    #url(r'^host(?P<host_id>\d+)/pro/(?<paymentoption>\w+)/$', 'billing.views.paypal_pro', name='billingpro'),        
 		#url(r'^checkout/$', 'billing.views.checkout', name='checkoutgeneric'),
 		#url(r'^checkout/host(?P<host_id>\d+)/$', 'billing.views.checkout', name='checkoutuser'),
 		#url(r'^paypal', 'billing.views.paypal_askformoney', name='paypalbase'), 	
)

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

blocbox/urls.py
from django.conf.urls import patterns, include, url
from core import views #it imports views from blocbox modeule so knows where to look for index files
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()

urlpatterns = patterns('',

		url(r'^$', views.index, name='index'),    
    url(r'beta/', views.beta, name='beta'), #Removing the caret so easier to hyperlink to
    url(r'^search/', views.search, name='search'),   
    url(r'^about/$', views.aboutblocbox, name='about'),
    url(r'^aboutblocbox/$', views.aboutblocbox, name='aboutblocbox'), 
    url(r'^hostprofile/host(?P<host_id>\d+)/$',views.hostprofile, name='hostprofile'),  
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    #need different URLs for the different modals on the dashboard - otherwise forms dont know what to submit
    url(r'^dashboard/track_id(?P<track_id>\d+)/',views.dashboard, name='dashboard'), 
    url(r'^dashboard/confirm_id(?P<confirm_id>\d+)/',views.dashboard, name='dashboard'),
    url(r'^dashboard/issue_id(?P<issue_id>\d+)/', views.dashboard, name='dashboard'),
    url(r'^dashboard/message(?P<message_trans_id>\d+)/', views.dashboard, name='dashboard'),
    url(r'^myblock/',views.myblock, name='myblock'),  
    url(r'^startashipment/$', views.startashipment, name='startashipment'),
    url(r'^nav_startashipment/$', views.nav_startashipment, name='nav_startashipment'),
    url(r'^nav_startafavor/$', views.nav_startafavor, name='nav_startafavor'),
    url(r'^startashipment/host(?P<host_id>\d+)/$', views.startashipment, name='startashipment'),
    url(r'^startashipment/host(?P<host_id>\d+)/days(?P<dayrangestart>\d+)to(?P<dayrangeend>\d+)/$', views.startashipment, name='startashipmentdays'),
    url(r'^startafavor/$', views.startafavor, name='startafavor'),
    url(r'^startafavor/host(?P<host_id>\d+)/$', views.startafavor, name='startafavor'),
    url(r'^shippackage/$', views.shippackage, name='shippackage_nohost'),  #this shouldn't really be used b/c not linked to a host  
    url(r'^shippackage/host(?P<host_id>\d+)/$', views.shippackage, name='shippackage'),
    url(r'^admin/', include(admin.site.urls)), 
    url(r'^signupconnect/host(?P<host_id>\d+)/$', views.signupconnect, name='signupconnect'),
    url(r'^connect/host(?P<host_id>\d+)/$', views.connectnewhost, name='connectnewhost'),
    url(r'^signup/', views.signupnoconnect, name='signupnoconnect'), 
    url(r'^hostsignup/', views.signuphost, name='signuphost'),
    url(r'^abouthosting/', views.abouthosting, name='abouthosting'),
    url(r'^nudgeaneighbor/', views.nudgeaneighbor, name='nudgeaneighbor'),
    url(r'^login/', views.userlogin, name='login'), # add this for the registration form
    url(r'^logout/$', views.user_logout, name='logout'), 		
    url(r'^almostfinished/$', views.waitlist_almostfinished, name='waitlist_almostfinished'),
    url(r'^waitlistconfirmation/$', views.waitlist_confirmation, name='waitlist_confirmation'),
 		#NOTE - removing the caret ^ before register so blocbox/register calls this as well
 		#the carret sasy beginning must match, the $ says end of string must match
 		#email stuff
 		url(r'^email/(?P<userinfo_id>\d+)/sendconfirmrequest/$', views.confirmconnect_mail, name='sendrequestconnect'),
    url(r'^(?P<host_id>\d+)/requestconnectconfirm/(?P<user_id>\d+)/$', views.confirmrequestconnect, name='confirmrequestconnect'), 		
 		url(r'^testing/', include('testing.urls')),
 		url(r'^scheduling/', include('schedule.urls')),
 		url(r'^passwordreset/',include('password_reset.urls')),
 		url(r'^messages/', include('django_messages.urls')),
 		url(r'^scheduling/', include('schedule.urls')),
 		#url(r'^payment/', views.payment, name='payment'),
 		url(r'^payment/', include('billing.urls', namespace='payment')), #because of the namepsac,e need to reeverse with reverse(payment:)
 		url(r'^datascience/', include('datasci.urls')),
 		
)



urlpatterns += staticfiles_urlpatterns()

#if want to import generic index view will look like
#url(r'^$', views.IndexView.as_view(), name='index'),
#url(r'^old/', views.oldindex, name='oldindex'), #old index

"""INCLUDE: when django ecounters include() it chops off whatever part matched and sents rest of the string
to the included URLconf for futher processing - so polls URLS are in their own URLconf polls.urls.py - they can be put aywhere
"""
from django.conf import settings

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

datasci/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from datasci import views 

admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'datasci.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
		url(r'^$', views.index, name='index'), 
    #url(r'datascience/', views.datascience_home, name='datasci'), #Removing the caret so easier to hyperlink to
  
    
)

schedule/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import DeleteEventView

urlpatterns = patterns(
    '',
    # urls for Calendars, the first one (list of avail calendars) loads at www.blocbox.co/scheduling/calendar and www.blocbox.co/scheduling 
    url(r'^calendar/$',
        ListView.as_view(queryset=Calendar.objects.all(),
                         template_name='schedule/calendar_list.html'),
        name="calendar_list"),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="year_calendar",
        kwargs={'periods': [Year], 'template_name': 'schedule/calendar_year.html'}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="tri_month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_tri_month.html'}),

		url(r'^calendar/bi_month/(?P<calendar_slug>[-\w]+)/$',                               
        'schedule.views.calendar_by_periods',                                             
        name="bi_month_calendar",               
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_bi_month.html'}),                                         
        #kwargs={'template_name': 'schedule/calendar_bi_month.html'}),
        #interpreting this use of kwargs: .. need to understand.. it is clearly reuired.. if i comment out doesnt worke ven though periods.month is called later

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="compact_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_compact_month.html'}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_month.html'}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="week_calendar",
        kwargs={'periods': [Week], 'template_name': 'schedule/calendar_week.html'}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="day_calendar",
        kwargs={'periods': [Day], 'template_name': 'schedule/calendar_day.html'}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar',
        name="calendar_home",
        ),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.create_or_edit_event',
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        'schedule.views.create_or_edit_event',
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        'schedule.views.event',
        name="event"),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name="delete_event"),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence"),

    #urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence_by_date"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence_by_date"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence_by_date"),

    #feed urls
    url(r'^feed/calendar/upcoming/(.*)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),
    #api urls
    url(r'^api/occurrences', 'schedule.views.api_occurrences', name='api_occurences'),

    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
)

django_messages/models.py
from django.db import models
from django.conf import settings
from django.db.models import signals
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

class MessageManager(models.Manager):

    def inbox_for(self, user):
        """
        Returns all messages that were received by the given user and are not
        marked as deleted.
        """
        return self.filter(
            recipient=user,
            recipient_deleted_at__isnull=True,
        )

    def outbox_for(self, user):
        """
        Returns all messages that were sent by the given user and are not
        marked as deleted.
        """
        return self.filter(
            sender=user,
            sender_deleted_at__isnull=True,
        )

    def trash_for(self, user):
        """
        Returns all messages that were either received or sent by the given
        user and are marked as deleted.
        """
        return self.filter(
            recipient=user,
            recipient_deleted_at__isnull=False,
        ) | self.filter(
            sender=user,
            sender_deleted_at__isnull=False,
        )


class Message(models.Model):
    """
    A private message from user to user
    """
    subject = models.CharField(_("Subject"), max_length=120)
    body = models.TextField(_("Body"))
    sender = models.ForeignKey(AUTH_USER_MODEL, related_name='sent_messages', verbose_name=_("Sender"))
    recipient = models.ForeignKey(AUTH_USER_MODEL, related_name='received_messages', null=True, blank=True, verbose_name=_("Recipient"))
    parent_msg = models.ForeignKey('self', related_name='next_messages', null=True, blank=True, verbose_name=_("Parent message"))
    sent_at = models.DateTimeField(_("sent at"), null=True, blank=True)
    read_at = models.DateTimeField(_("read at"), null=True, blank=True)
    replied_at = models.DateTimeField(_("replied at"), null=True, blank=True)
    sender_deleted_at = models.DateTimeField(_("Sender deleted at"), null=True, blank=True)
    recipient_deleted_at = models.DateTimeField(_("Recipient deleted at"), null=True, blank=True)
    
    objects = MessageManager()
    
    def new(self):
        """returns whether the recipient has read the message or not"""
        if self.read_at is not None:
            return False
        return True
        
    def replied(self):
        """returns whether the recipient has written a reply to this message"""
        if self.replied_at is not None:
            return True
        return False
    
    def __unicode__(self):
        return self.subject
    
    def get_absolute_url(self):
        return ('messages_detail', [self.id])
    get_absolute_url = models.permalink(get_absolute_url)
    
    def save(self, **kwargs):
        if not self.id:
            self.sent_at = timezone.now()
        super(Message, self).save(**kwargs) 
    
    class Meta:
        ordering = ['-sent_at']
        verbose_name = _("Message")
        verbose_name_plural = _("Messages")
        
def inbox_count_for(user):
    """
    returns the number of unread messages for the given user but does not
    mark them seen
    """
    return Message.objects.filter(recipient=user, read_at__isnull=True, recipient_deleted_at__isnull=True).count()

# fallback for email notification if django-notification could not be found
if "notification" not in settings.INSTALLED_APPS:
    from django_messages.utils import new_message_email
    signals.post_save.connect(new_message_email, sender=Message)

django_messages/templates/django_messages/base.html
<!--this is /blocbox/django_messages/templates/django_messages/base.html, extends blocbox/base.html, extended by other messagign pages -->
{% extends "blocbox/base.html" %}

{% load i18n %}
{% load url from future %} 
{% block bodyclass %}about{% endblock %}

{% with active_page=inbox %}  

{% block content %}
<div class="content container-fluid fillpage whitebackground relativediv">

{% block sidebar %}

    <div class="row margintop60px marginbottom10px mobilehide">
        <a href="/dashboard/" class="col-xs-2 col-xs-offset-1 subnavtext textcenter">DASHBOARD</a>
        <a href="/messages/inbox/" class="col-xs-2 subnavtextcurrent textcenter">MESSAGES ({% load inbox %}	{% inbox_count %} NEW)</a>
        <a href="/myblock/" class="col-xs-2 subnavtext textcenter">MY BLOCK</a>
        <p class="col-xs-2 subnavtext textcenter">PROFILE</p>
        <p class="col-xs-2 subnavtext textcenter">ACCOUNT</p>
        <div class="col-xs-10 col-xs-offset-1">
            <div class="profileboxline100"></div>
        </div>
    </div>
{% endblock %} <!--sidebar-->

  

	<div class="col-xs-12 col-sm-12">
		
		<div class="row"> <!--top navigation row for the subpages-->
	
    	<a href="/messages/inbox" class="col-xs-2 col-xs-offset-1  {% ifequal request.path "/messages/inbox/" %} subnavtextcurrent {% endifequal %}  subnavtext textcenter">{% trans "INBOX" %} ({% load inbox %}	{% inbox_count %})</a>
    	<a href="/messages/compose/" class="col-xs-2 {% ifequal request.path "/messages/compose/" %} subnavtextcurrent {% endifequal %} subnavtext textcenter">{% trans "COMPOSE" %} </a>
    	<a href="/messages/outbox/" class="col-xs-2 {% ifequal request.path "/messages/outbox/" %} subnavtextcurrent {% endifequal %} subnavtext textcenter">{% trans "SENT" %}</a>
    	<a href="/messages/trash/" class="col-xs-2 {% ifequal request.path "/messages/archive/" %}  subnavtextcurrent {% endifequal %}  subnavtext textcenter">{% trans "ARCHIVE" %}</a>
    	<a href="/messages/messagesettings/" class="col-xs-2 {% ifequal request.path "/messages/messagesettings/" %}  subnavtextcurrent {% endifequal %} subnavtext textcenter">SETTINGS</a>
		
		</div> <!--row-->

		{% block messagingcontent %}
		{% endblock %}

	</div>

</div>
{% endblock %} <!--content-->

{% endwith %}

django_messages/templates/django_messages/compose.html
{% extends "django_messages/base.html" %} 
{% load i18n %} 
{% block title %}Compose{% endblock %}
{% with active_page=compose %}  
{% block messagingcontent %} 


<div class="row margintopbottom30px">
   <div class="col-xs-6 col-xs-offset-3">
        <form action="" method="post">
        {% csrf_token %} 
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="{% trans "Send" %} &raquo;"/>
        </form>
    </div>
</div>

{% endblock %}

{% endwith %}

django_messages/templates/django_messages/inbox.html
<!--	this is django_messages/templates/django_messages/inbox.html
			it extends django_messages/templates/django_messages/base.html, which extends blocbox/base.html
			URL is www.blocbox.co/messages/inbox -->

{% extends "django_messages/base.html" %} 
{% load i18n %} 
{% load url from future %}
{% block title %}Inbox{% endblock %}


{% block messagingcontent %}

<div class="row">
   <div class="col-xs-10 col-xs-offset-1 messbox margintop20px">
       {% if message_list %} 
       <!--top row showing Sender, Subjec,t Received, Action, trans=translate, this was  -->
           <div class="col-xs-10 col-xs-offset-1">
               {% for message in message_list %} 
               <div class="row inboxmessbox ">
                   <div class="col-xs-2 paddingtopbottom30px">
                    <img class="dashpic" src=""  /> 
                  </div>
                   <p class="col-xs-2 textcenter paddingtopbottom30px">{{ message.sender }}</p>
                   <div class="col-xs-4 paddingtopbottom30px">
                       {% if message.new %}<strong>{% endif %}
                       {% if message.replied %}<em>{% endif %}
                       <a href="{{message.get_absolute_url }}">{{ message.subject }}</a>
                       {% if message.replied %}</em>{% endif %}
                       {% if message.new %}</strong>{% endif %}</div>
                   <p class="col-xs-3 textcenter paddingtopbottom30px">{{ message.sent_at|date:_("DATETIME_FORMAT") }}</p>
                   <p class="col-xs-1 textcenter paddingtopbottom30px"><a href="{% url 'messages_delete' message.id %}">{% trans "delete" %}</a></p>
               </div>
               {% endfor %}
           </div>
       {% else %}
       <p>{% trans "No messages." %}</p>
       {% endif %}  
    </div>
</div>
    


{% endblock %}

django_messages/templates/django_messages/new_message.html
{% load i18n %}
{% load url from future %}
{% block title %}New Message{% endblock %}
{% blocktrans with recipient=message.recipient sender=message.sender %}Hello {{ recipient }},

you received a private message from {{ sender }} with
the following contents:{% endblocktrans %}

{{ message.body|safe }}

--
{% blocktrans %}Sent from {{ site_url }}{% endblocktrans %}
{% trans "Inbox" %}: {{ site_url }}{% url 'messages_inbox' %}
{% trans "Reply" %}: {{ site_url }}{% url 'messages_reply' message.pk %}     

django_messages/templates/django_messages/outbox.html
{% extends "django_messages/base.html" %} 
{% load i18n %} 
{% load url from future %}

{% block title %}Outbox{% endblock %}


{% block messagingcontent %} 

{% if message_list %} 
<table class="table messages"> 
    <thead>
        <tr><th>{% trans "Recipient" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Sent" %}</th><th>{% trans "Action" %}</th></tr>
    </thead>
    <tbody>
{% for message in message_list %} 
    <tr>
        <td>{{ message.recipient }}</td>
        <td>
        <a href="{{ message.get_absolute_url }}">{{ message.subject }}</a>
        </td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'messages_delete' message.id %}?next={% url 'messages_outbox' %}">{% trans "delete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}   
{% endblock %}

django_messages/templates/django_messages/trash.html
{% extends "django_messages/base.html" %} 
{% load i18n %} 
{% load url from future %}
{% block title %}Trash{% endblock %}

{% block messagingcontent %} 


{% if message_list %} 
<table class="table messages">
    <thead>
        <tr><th>{% trans "Sender" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Date" %}</th><th>{% trans "Action" %}</th></tr>
    </thead>
    <tbody>
{% for message in message_list %} 
    <tr>
        <td>{{ message.sender }}</td>
        <td> 
        {{ message.subject }}
        </td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'messages_undelete' message.id %}">{% trans "undelete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}   
<br />
<p>{% trans "Deleted Messages are removed from the trash at unregular intervals, don't rely on this feature for long-time storage." %}</p>
{% endblock %}

django_messages/templates/django_messages/view.html
{% extends "django_messages/base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}View Message{% endblock %}
 

{% block messagingcontent %}


<dl class="message-headers">
    <dt>{% trans "Subject" %}</dt>
    <dd><strong>{{ message.subject }}</strong></dd>
    <dt>{% trans "Sender" %}</dt>
    <dd>{{ message.sender }}</dd>
    <dt>{% trans "Date" %} </dt>
    <dd>{{ message.sent_at|date:_("DATETIME_FORMAT")}}</dd>
    <dt>{% trans "Recipient" %}</dt>
    <dd>{{ message.recipient }}</dd>
</dl>
{{ message.body|linebreaksbr }}<br /><br />

{% ifequal message.recipient.pk user.pk %}
<a href="{% url 'messages_reply' message.id %}">{% trans "Reply" %}</a>
{% endifequal %}
<a href="{% url 'messages_delete' message.id %}">{% trans "Delete" %}</a>

{% comment %}Example reply_form integration
{% if reply_form %}
<h1>{% trans "Compose reply"%}</h1>
<form action="{% url 'messages_reply' message.id %}" method="post">
{% csrf_token %}
<table>
{{ reply_form.as_table }}
</table>
<input type="submit" value="{% trans "Send" %} &raquo;"/>
</form>
{% endif %}
{% endcomment %}
{% endblock %}