billing/urls.py
#This is blocbox/billing/urls.py
from django.conf.urls import patterns, include, url
from core import views #it imports views from blocbox modeule so knows where to look for index files
#from django.conf.urls.defaults import * #that was in the paypal ipn
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from billing import views 
from paypal.standard.ipn import views
admin.autodiscover()


#url patterns preceded by blocbox.co/payment - the namespace is payment, so need to reverse call with, eg payment:paypal_ipn
urlpatterns = patterns('',
		#Base views - defined in billing/views.py
		url(r'^$', 'paypal.standard.ipn.views.ask_for_money', name='payment_default'), #blocbox.co/payment, defaults o host_id=2 which is John
		url(r'^host(?P<host_id>\d+)/$', 'billing.views.base', name='billingbase'), #blocbox.co/payment/host2
		url(r'^host(?P<host_id>\d+)/days(?P<dayrangestart>\d+)to(?P<dayrangeend>\d+)/$', 'billing.views.base', name='billingbase'), 
		#STANDARD-IPN URLs - view in paypal/standard/ipn/views.py		
		url(r'^host(?P<host_id>\d+)/ipn/(?P<favortype>\w+)/(?P<paymentoption>\w+)/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask'), #blocbox.co/payment/host2/<TYPE?
		url(r'^host(?P<host_id>\d+)/days(?P<dayrangestart>\d+)to(?P<dayrangeend>\d+)/ipn/(?P<favortype>\w+)/(?P<paymentoption>\w+)/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask'),
		url(r'^ipn/host(?P<host_id>\d+)/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask_noamount'), #blocbox.co/payment/host2 - not really relevant - Default - Package Amount
		url(r'^ipn/notify(?P<host_id>\d+)/$', 'paypal.standard.ipn.views.ipn', name='paypal_ipn_notify'), #this is the notify_url	
		url(r'^ipn/$', 'paypal.standard.ipn.views.ask_for_money', name='ipn_ask_nohost'), #blocbox.co/payment/ipn - NOT FUNCTION B/C DOESN'T LINK TO HOST
    url(r'^ipn/return/$', 'paypal.standard.ipn.views.ipn_return_successful', name='ipn_return_successful'), #Eventually may need a return URL
    #STANDARD-PDT URLS
    #PRO URLS
    #url(r'^pro$', 'billing.views.paypal_pro', name='billingpro'), #no real purpose to this bc not linked to a host
    #url(r'^host(?P<host_id>\d+)/pro/(?<paymentoption>\w+)/$', 'billing.views.paypal_pro', name='billingpro'),        
 		#url(r'^checkout/$', 'billing.views.checkout', name='checkoutgeneric'),
 		#url(r'^checkout/host(?P<host_id>\d+)/$', 'billing.views.checkout', name='checkoutuser'),
 		#url(r'^paypal', 'billing.views.paypal_askformoney', name='paypalbase'), 	
)

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

blocbox/urls.py
from django.conf.urls import patterns, include, url
from core import views #it imports views from blocbox modeule so knows where to look for index files
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()

urlpatterns = patterns('',

		url(r'^$', views.index, name='index'),    
    url(r'beta/', views.beta, name='beta'), #Removing the caret so easier to hyperlink to
    url(r'^search/', views.search, name='search'),   
    url(r'^about/$', views.aboutblocbox, name='about'),
    url(r'^aboutblocbox/$', views.aboutblocbox, name='aboutblocbox'), 
    url(r'^hostprofile/host(?P<host_id>\d+)/$',views.hostprofile, name='hostprofile'),  
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    #need different URLs for the different modals on the dashboard - otherwise forms dont know what to submit
    url(r'^dashboard/track_id(?P<track_id>\d+)/',views.dashboard, name='dashboard'), 
    url(r'^dashboard/confirm_id(?P<confirm_id>\d+)/',views.dashboard, name='dashboard'),
    url(r'^dashboard/issue_id(?P<issue_id>\d+)/', views.dashboard, name='dashboard'),
    url(r'^dashboard/message(?P<message_trans_id>\d+)/', views.dashboard, name='dashboard'),
    url(r'^myblock/',views.myblock, name='myblock'),  
    url(r'^startashipment/$', views.startashipment, name='startashipment'),
    url(r'^nav_startashipment/$', views.nav_startashipment, name='nav_startashipment'),
    url(r'^nav_startafavor/$', views.nav_startafavor, name='nav_startafavor'),
    url(r'^startashipment/host(?P<host_id>\d+)/$', views.startashipment, name='startashipment'),
    url(r'^startashipment/host(?P<host_id>\d+)/days(?P<dayrangestart>\d+)to(?P<dayrangeend>\d+)/$', views.startashipment, name='startashipmentdays'),
    url(r'^startafavor/$', views.startafavor, name='startafavor'),
    url(r'^startafavor/host(?P<host_id>\d+)/$', views.startafavor, name='startafavor'),
    url(r'^shippackage/$', views.shippackage, name='shippackage_nohost'),  #this shouldn't really be used b/c not linked to a host  
    url(r'^shippackage/host(?P<host_id>\d+)/$', views.shippackage, name='shippackage'),
    url(r'^admin/', include(admin.site.urls)), 
    url(r'^signupconnect/host(?P<host_id>\d+)/$', views.signupconnect, name='signupconnect'),
    url(r'^connect/host(?P<host_id>\d+)/$', views.connectnewhost, name='connectnewhost'),
    url(r'^signup/', views.signupnoconnect, name='signupnoconnect'), 
    url(r'^hostsignup/', views.signuphost, name='signuphost'),
    url(r'^abouthosting/', views.abouthosting, name='abouthosting'),
    url(r'^nudgeaneighbor/', views.nudgeaneighbor, name='nudgeaneighbor'),
    url(r'^login/', views.userlogin, name='login'), # add this for the registration form
    url(r'^logout/$', views.user_logout, name='logout'), 		
    url(r'^almostfinished/$', views.waitlist_almostfinished, name='waitlist_almostfinished'),
    url(r'^waitlistconfirmation/$', views.waitlist_confirmation, name='waitlist_confirmation'),
 		#NOTE - removing the caret ^ before register so blocbox/register calls this as well
 		#the carret sasy beginning must match, the $ says end of string must match
 		#email stuff
 		url(r'^email/(?P<userinfo_id>\d+)/sendconfirmrequest/$', views.confirmconnect_mail, name='sendrequestconnect'),
    url(r'^(?P<host_id>\d+)/requestconnectconfirm/(?P<user_id>\d+)/$', views.confirmrequestconnect, name='confirmrequestconnect'), 		
 		url(r'^testing/', include('testing.urls')),
 		url(r'^scheduling/', include('schedule.urls')),
 		url(r'^passwordreset/',include('password_reset.urls')),
 		url(r'^messages/', include('django_messages.urls')),
 		url(r'^scheduling/', include('schedule.urls')),
 		#url(r'^payment/', views.payment, name='payment'),
 		url(r'^payment/', include('billing.urls', namespace='payment')), #because of the namepsac,e need to reeverse with reverse(payment:)
 		url(r'^datascience/', include('datasci.urls')),
 		
)



urlpatterns += staticfiles_urlpatterns()

#if want to import generic index view will look like
#url(r'^$', views.IndexView.as_view(), name='index'),
#url(r'^old/', views.oldindex, name='oldindex'), #old index

"""INCLUDE: when django ecounters include() it chops off whatever part matched and sents rest of the string
to the included URLconf for futher processing - so polls URLS are in their own URLconf polls.urls.py - they can be put aywhere
"""
from django.conf import settings

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

datasci/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from datasci import views 

admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'datasci.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
		url(r'^$', views.index, name='index'), 
    #url(r'datascience/', views.datascience_home, name='datasci'), #Removing the caret so easier to hyperlink to
  
    
)

schedule/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import DeleteEventView

urlpatterns = patterns(
    '',
    # urls for Calendars, the first one (list of avail calendars) loads at www.blocbox.co/scheduling/calendar and www.blocbox.co/scheduling 
    url(r'^calendar/$',
        ListView.as_view(queryset=Calendar.objects.all(),
                         template_name='schedule/calendar_list.html'),
        name="calendar_list"),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="year_calendar",
        kwargs={'periods': [Year], 'template_name': 'schedule/calendar_year.html'}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="tri_month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_tri_month.html'}),

		url(r'^calendar/bi_month/(?P<calendar_slug>[-\w]+)/$',                               
        'schedule.views.calendar_by_periods',                                             
        name="bi_month_calendar",               
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_bi_month.html'}),                                         
        #kwargs={'template_name': 'schedule/calendar_bi_month.html'}),
        #interpreting this use of kwargs: .. need to understand.. it is clearly reuired.. if i comment out doesnt worke ven though periods.month is called later

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="compact_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_compact_month.html'}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_month.html'}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="week_calendar",
        kwargs={'periods': [Week], 'template_name': 'schedule/calendar_week.html'}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="day_calendar",
        kwargs={'periods': [Day], 'template_name': 'schedule/calendar_day.html'}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar',
        name="calendar_home",
        ),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.create_or_edit_event',
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        'schedule.views.create_or_edit_event',
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        'schedule.views.event',
        name="event"),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name="delete_event"),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence"),

    #urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence_by_date"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence_by_date"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence_by_date"),

    #feed urls
    url(r'^feed/calendar/upcoming/(.*)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),
    #api urls
    url(r'^api/occurrences', 'schedule.views.api_occurrences', name='api_occurences'),

    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
)

connections/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.conf import settings
from core.models import UserInfo


    
#Define the connection relation
class ConnectionManager(models.Manager):
    
    def connection_for_user(self, user):
        connections = []
        for connection in self.filter(host_user=user).select_related(depth=1):
            connections.append({"neighbor": connection.host_user, "connection": connection})
        for connection in self.filter(end_user=user).select_related(depth=1):
            connections.append({"neighbor": connection.end_user, "connection": connection})
        return connections
    
    def are_neighbors(self, user1, user2):
        if self.filter(end_user=user1, host_user=user2).count() > 0:
            return True
        if self.filter(end_user=user2, host_user=user1).count() > 0:
            return True
        return False
    
    def remove(self, user1, user2):
        if self.filter(end_user=user1, host_user=user2):
            connection = self.filter(end_user=user1, host_user=user2)
        elif self.filter(end_user=user2, host_user=user1):
            connection = self.filter(end_user=user2, host_user=user1)
        connection.delete()
        
class Connection(models.Model):
    #A connection is a bi-directional association between two users who
    #have both agreed to the association.
    #from site: https://github.com/jtauber/django-friends/blob/master/friends/models.py
        
    host_user = models.ForeignKey(UserInfo, related_name="host_id") #was to_user
    end_user = models.ForeignKey(UserInfo, related_name="enduser_id") #was from_user
    # @@@ relationship types
    added = models.DateField(default=datetime.date.today)
    intro_message = models.CharField("Intro Message to Host from User", max_length=300, null=True,blank=True)
    pickup_time = models.CharField("Preferred Pickup Time", max_length=150, blank=True, null=True)
    testfield=models.CharField(max_length=200,blank=True, null=True)
    objects = ConnectionManager()
    
    class Meta:
        unique_together = (('host_user', 'end_user'),)

core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.conf import settings
from core.models import UserInfo
from connections.models import Connection

class UserForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)
    zipcode = forms.CharField(label="Zip Code")

    class Meta:
        model = UserInfo
        fields = ('email', 'password', 'password2', 'zipcode', 'hostinterest', 
            'first_name', 'last_name', 'zipcode', 'st_address1', 'st_address2', 'city', 'state',
            'about_me', 'intro_message', 'pickup_time', 'FBlink', 'imageurl', 'userrating', 'host',
            'need_storage', 'need_petcare', 'need_housesitting', 'need_rentals', 'need_laundry', 'need_letin',
    				'need_childcare', 'need_plantcare', 'need_lawn', 'need_carsharing', 'need_housemaint', 'need_autocare', 'need_other'
            )

#The hostPRofileForm should include the UserProfileForm and other stuff specific to host
#Need a second about_me field for hosts that is required
class HostForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('host_aboutme', 'services_offered', 'availability', 'hostrating',)
   
#connect form for useres that are already registered, still works off of userinfo 
class ConnectForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('about_me', 'intro_message', 'pickup_time', 'FBlink', 'imageurl', 'userrating', 'host',
            'need_storage', 'need_petcare', 'need_housesitting', 'need_rentals', 'need_laundry', 'need_letin',
    				'need_childcare', 'need_plantcare', 'need_lawn', 'need_carsharing', 'need_housemaint', 'need_autocare', 'need_other'
            )

core/templates/blocbox/aboutblocbox.html
<!--this is core/templates/blocbox/aboutblocbox.html - url is blocbox.co/abouthosting. it extends base.html-->
{% extends "blocbox/base.html" %} {% load staticfiles %} {% block title %}About{% endblock %} {% block headafter %} {% endblock %} {% block content %}
<div class="content container-fluid">
    <!--this is the container that surrounds the form, too short -->

    <br>
    <br>
    <h3 class="">John to add FAQs/About BlocBox</h3>

</div>
{% endblock %}

core/templates/blocbox/almost-finished.html
{% extends "blocbox/basewaitlist.html" %}
<!--this is blocbox/core/templates/bocbox/almost-finished.html, url is http://www.blocbox.co/almostfinished-->
{% load staticfiles %} 
{% block title %} Almost Finished... {% endblock %}

{% block topcontent %}

 	<div class="row-fluid fullheight">
    	<br> <br> 
  	<h1>Almost Finished...</h1>
  	<h3 >Please confirm your subscription to our waitlist by clicking on the link in the email we just sent you.</h3>
 	</div>

{% endblock %}

core/templates/blocbox/connect-already-registered.html
<!--this is blocbox/core/templates/blocbox/connect-already-registered, ULR is http://www.blocbox.co/connect/host2 - where 2 = userid of host
		this does NOT extend sign-up-withoutconnect because ther eis not a sign up form.. extends baseesignup-->
{% extends "blocbox/base.html" %}
{% load staticfiles %} 
{% load staticfiles %}
{% block title %}Connect with {{host.first_name}}{% endblock %}

{% block content %}



 			
<div class="content container-fluid"> <!--this is the container that surrounds the form, too short -->
	<br>
	<div class="row">
  	<div class="col-xs-12 col-sm-8 col-sm-offset-2">
		
		{% if requested %}
	  <br> <br>
    <h3>
      		Thank you for Requesting to Connect with {{host.first_name }}! <br>
      		You'll receive a notification when {{ host.first_name }} confirms your request to connect. <br>
      		In the meantime, <a href="/login/">login to your account</a> to visit your dashboard and update your account preferences and user information.
    </h3>
 		<br> <br> <br> <br> <br>
		{% else %}

  		<!--Start Registration Form -->
     	<form class="form-horizontal margintop30px" role="form" method="post" action="." enctype="multipart/form-data">
       		{% csrf_token %}
        	{{ connect_form.non_field_errors }}
        	
     			<!--<div class="col-sm-9 col-sm-offset-3">-->
     			<br>
     			<h3 class="margintop20px"> Connect with {{host.first_name}}</h3>
     				  
					<h5 class="marginbottom20px">Before you connect, {{host.first_name}} will need to confirm your request.  
        			The information you provide below will help {{host.first_name}} confirm you as a neighbor.</h5>
  
  				<!--Intro MEssage -->
  				<div class="form-group">  {{ connect_form.intro_message.errors }}
        			<div class="row">
            		<div class="col-sm-12 col-sm-5">
                	<label for="id_intro_message">Introduce Yourself to {{host.first_name}} </label>
            		</div>
            			<div class="col-xs-12 col-sm-7">
                		<input type="text" class="form-control" name="intro_message" id="id_intro_message"  
    									placeholder="Hello!... (350 Character Limit)">
            			</div>
        			</div> <!--row-->  			
    			</div>	<!--form-group-->
    
    
    	<!--time of day typically pick up packages -->
    	<div class="form-group">  {{ connect_form.pickup_time.errors }}
        <div class="row">
            <div class="col-xs-12 col-sm-5">
                <label for="id_pickup_time">Time of day you would typically pick up packages</label>
            </div>
            <div class="col-xs-12 col-sm-7">
                <input type="text" class="form-control" name="pickup_time" id="id_pickup_time"  
    					placeholder="Describe in 100 characters">
            </div>  <!--row-->       	
        </div>		
        
        						
						<!--add hidden fields for host_user and user_id -- dont like this method but will have tow rok -->
						{{ connect_form.host_user.errors }}
						<input type="hidden" name="host_user" value= {{ host.id }} id="id_host_user">
						{{ connect_form.end_user.errors }}
						<input type="hidden" name="end_user" value= {{ enduser.id }} id="id_end_user">
							
    	</div>	<!--form-group -->


         	<div class="col-xs-10 col-xs-offset-1 margintop30px profileboxline100"></div>

 					<div class="form-group"> <!--submit button--> 						
    				<div class="row col-xs-10 col-xs-offset-1 margintop20px"> <!--submit button -->                                        
                     		<div class="col-xs-offset-7 col-xs-5">
                        	 	<button type="submit" name="submit" class="bluebutton">Request to Connect</button>
                     		</div> <!--col-->                                                   
             </div> <!--row for submit button-->   				
    			</div> <!--form-group, submit button -->

    			<br><br><br><br><br>

  </form>  <!--end form -->
   		
   	
{% endif %} <!--else if not requested already -->

	</div>   <!--end containing column -->
</div> <!--end row containing row-->
</div> <!--end of top divider  -->

{% endblock %}

 					<!--other use cases check boxes - not including in this form, because it will probably over-write what is already on the table
 							can add this back in later... 
         	<div class="row"> 
                   <h5 class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 margintop20px">What other services are you interested in receiving? (Optional)</h5>
         	</div>  

					<div class="form-group"> 
             	<div class="row">
                  <div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-2">
                       <label class="checkbox-inline"> <input class="offersbox" type="checkbox" id="id_need_storage" name="need_storage">Storage</label>
                  </div>
                  
                  <div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
											<label class="checkbox-inline"> <input type="checkbox" id="id_need_petcare" name="need_petcare"> Pet Care</label>
                	</div>
                	
                	<div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
											<label class="checkbox-inline"> <input type="checkbox" id="id_need_housesitting" name="need_housesitting"> House Sitting </label>
                	</div>
                	
                	<div class="col-xs-10 col-xs-offset-1 col-sm-3 col-sm-offset-0">
                			<label class="checkbox-inline"> <input type="checkbox" id="id_need_rentals" name="need_rentals"> Equipment or Party Rentals </label>
                  </div>
              	
             </div> 
              	
             <div class="row paddingtop5px">
                    <div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-2">
                         <label class="checkbox-inline"> <input type="checkbox" id="id_need_laundry" name="need_laundry"> Laundry	</label>
                    </div>
                    
                    <div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
												<label class="checkbox-inline"> <input type="checkbox" id="id_need_plantcare" name="need_plantcare"> Plant Care </label>
                  	</div>
                 	
                 		<div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
												<label class="checkbox-inline"> <input type="checkbox" id="id_need_childcare" name="need_childcare"> Child Care </label>
                 	 	</div>
                  
                  	<div class="col-xs-10 col-xs-offset-1 col-sm-3 col-sm-offset-0">
                        <label class="checkbox-inline">	<input type="checkbox" id="id_need_letin" name="need_letin"> Let Repairperson In </label>
                  	</div>
             	</div> 
               
               <div class="row paddingtop5px">
               	  <div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-2">
											<label class="checkbox-inline"> 	<input type="checkbox" id="id_need_lawn" name="need_letin"> Lawn Care </label>
                  </div>
                     
                  <div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
											<label class="checkbox-inline"> <input type="checkbox" id="id_need_carsharing" name="need_carsharing"> Car Sharing </label>
                  </div>
                    
                  <div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
											<label class="checkbox-inline">	<input type="checkbox" id="id_need_meals" name="need_meals"> Community Meals </label>
                  </div>
                  
                 	<div class="col-xs-10 col-xs-offset-1 col-sm-3 col-sm-offset-0">
                     <label class="checkbox-inline"> <input type="checkbox" id="id_need_housemaint" name="need_housemaint"> House Maintenance </label>
                  </div>
                  
               </div> 
						</div>
						

                <div class="form-group"> 
                    <div class="row margintop10px">
                        <label for="id_need_other" class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">What else could {{host.first_name}} help you with?</label>
                        </div>
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
                                    <input type="text" class="form-control" name="need_other" id="id_need_other"  placeholder="Write in to request another service">
                        </div>
                    </div> 
                </div> 
					  END other use cases check boxes-->

    				

core/templates/blocbox/myblockjesslatest.html
<!--this is blocbox/templates/myblock.html -- URL is www.blocbox.co/myblock, linked from dashboard -->
{% extends "blocbox/base.html" %}
{% load staticfiles %} 
{% block title %}My Block{% endblock %}

{% block headafter %} {% endblock %} 

{% block content %}

<br>
<h3>DELME - TESTING - THIS IS THE MY BLOCK PAGE</h3>



{% endblock %} 